# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '36 11 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Oops, looks like the wizards have not seen this page in their recipe book!'
        stale-pr-message: 'The stove is burning for too long, turn off the fire wizards!'
        stale-issue-label: 'There is a problem with this recipe, it does not tell for what'
        stale-pr-label: 'Hmmm... what might this be?'
